kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-pvc-jegan # Replace 'jegan' with your name
spec:
  selector:
    labels:
      name: jegan # Replace 'jegan' with your name
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  volumeMode: Filesystem
