apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task1
spec:
  steps:
  - name: step-1
    image: ubuntu
    command:
    - echo
    args:
    - Task1 - Step1

  - name: step-2
    image: ubuntu
    command:
    - echo
    args:
    - Task1 - Step2
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task2
spec:
  steps:
  - name: step-1
    image: ubuntu
    command:
    - echo
    args:
    - Task2 - Step1

  - name: step-2
    image: ubuntu
    command:
    - echo
    args:
    - Task2 - Step2

  - name: step-3
    image: ubuntu
    command:
    - echo
    args:
    - Task2 - Step3

---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: first-pipeline
spec:
  tasks:
  - name: pipeline-task1
    taskRef: 
      kind: Task
      name: task1

  - name: pipeline-task2
    runAfter:
    - pipeline-task1 
    taskRef: 
      kind: Task
      name: task2
