apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: taskrun-with-emptydir-
spec:
  workspaces:
  - name: my-folder
    emptyDir: {}

  taskSpec:
    workspaces:
    - name: my-folder
    steps:
    - name: step-1 
      image: ubuntu
      script: |
        echo "Created by step-1" > $(workspaces.my-folder.path)/file.txt

    - name: step-2 
      image: ubuntu
      script: |
        cat $(workspaces.my-folder.path)/file.txt
