apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello-task-with-params
spec:
  params:
  - name: message
    type: string
    description: this is a user-defined variable that accepts any message
    default: "Hello Tekton Task !"
  steps:
  - name: step1
    image: ubuntu
    command: 
    - echo
    args:
    - $(params.message)
